version: '3.7'

services:
  weather-bot:
    build:
      context: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
    - 80:80
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - weather-redis-data:/data
    restart: unless-stopped

volumes:
  weather-redis-data:
