[tool.poetry]
name = "weather_bot"
version = "0.1.0"
description = ""
authors = ["Vital D. <admin@netin.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
aiogram = "2.9.2"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
